services:
    app.factory.letter:
        class: App\Factory\LetterFactory
        arguments:
            - '%app.model.letter.class%'
            - '@app.repository.letter'

    app.factory.letter_line:
        class: App\Factory\LetterLineFactory
        arguments:
            - '%app.model.letter_line.class%'
            - '@app.repository.letter_line'
