sylius_resource:
    resources:
        app.letter:
            classes:
                model: App\Entity\Letter
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                factory: App\Factory\LetterFactory
                form: App\Form\LetterType
                repository: App\Repository\LetterRepository
        app.letter_line:
            classes:
                model: App\Entity\LetterLine
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                factory: App\Factory\LetterLineFactory
                form: App\Form\LetterLineType
                repository: App\Repository\LetterLineRepository
        app.tag:
            classes:
                model: App\Entity\Tag
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                form: App\Form\TagType
                repository: App\Repository\TagRepository
        app.training:
            classes:
                model: App\Entity\Training
                controller: Enhavo\Bundle\AppBundle\Controller\ResourceController
                form: App\Form\TrainingType
                repository: App\Repository\TrainingRepository
