app_frontend_training_index:
    path: /training/index
    defaults:
        _controller: App\Controller\TrainingController:indexAction

app_frontend_training_training:
    path: /training/train/{slug}/{type}
    defaults:
        _controller: App\Controller\TrainingController:trainAction

app_frontend_training_list_letters:
    path: /training/list-letters/{slug}
    defaults:
        _controller: App\Controller\TrainingController:listLettersAction

app_frontend_training_adjust_letter_score:
    path: /training/adjust-letter-score/{letterId}/{correct}
    defaults:
        _controller: App\Controller\TrainingController:adjustLetterScoreAction

app_frontend_training_change_letter_score:
    path: /training/change-letter-score/{letterId}/{value}
    defaults:
        _controller: App\Controller\TrainingController:changeLetterScoreAction

app_frontend_training_toggle_letter_active:
    path: /training/toggle-letter-active/{letterId}
    defaults:
        _controller: App\Controller\TrainingController:toggleLetterActiveAction
