<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Enhavo\Bundle\DoctrineExtensionBundle\EnhavoDoctrineExtensionBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    winzou\Bundle\StateMachineBundle\winzouStateMachineBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle::class => ['all' => true],
    WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Sylius\Bundle\ResourceBundle\SyliusResourceBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    Enhavo\Bundle\AppBundle\EnhavoAppBundle::class => ['all' => true],
    Enhavo\Bundle\FormBundle\EnhavoFormBundle::class => ['all' => true],
    Enhavo\Bundle\NavigationBundle\EnhavoNavigationBundle::class => ['all' => true],
    Enhavo\Bundle\MediaBundle\EnhavoMediaBundle::class => ['all' => true],
    Enhavo\Bundle\BlockBundle\EnhavoBlockBundle::class => ['all' => true],
    Enhavo\Bundle\ContentBundle\EnhavoContentBundle::class => ['all' => true],
    Enhavo\Bundle\PageBundle\EnhavoPageBundle::class => ['all' => true],
    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle::class => ['all' => true],
    Enhavo\Bundle\RoutingBundle\EnhavoRoutingBundle::class => ['all' => true],
    Enhavo\Bundle\UserBundle\EnhavoUserBundle::class => ['all' => true],
    Enhavo\Bundle\DashboardBundle\EnhavoDashboardBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Enhavo\Bundle\SettingBundle\EnhavoSettingBundle::class => ['all' => true],
    Enhavo\Bundle\BackupBundle\EnhavoBackupBundle::class => ['all' => true],
];
